version: '3'

services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - '8080:80'
        volumes:
            - .:/app/
        links:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/app/

    db:
        restart: always
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        volumes:
            - .:/app/
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : <MySQL Port running inside container>
            - '3306:3306'
        expose:
            - '3306'

    cron:
        build:
            context: .
            dockerfile: docker/cron/Dockerfile
        volumes:
            - .:/app/
        depends_on:
            - php
